# Generated by Django 2.0.7 on 2018-07-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_ID', models.CharField(blank=True, max_length=10)),
                ('Car_MakeName', models.CharField(blank=True, max_length=30)),
                ('Car_Model', models.CharField(blank=True, max_length=30)),
                ('Car_Series', models.CharField(blank=True, max_length=30)),
                ('Car_SeriesYear', models.IntegerField(blank=True)),
                ('Car_PriceNew', models.IntegerField(blank=True)),
                ('Car_EngineSize', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('Car_FuelSystem', models.CharField(blank=True, max_length=10)),
                ('Car_TankCapacity', models.IntegerField(blank=True)),
                ('Car_Power', models.CharField(blank=True, max_length=10)),
                ('Car_SeatingCapacity', models.CharField(blank=True, max_length=10)),
                ('Car_StandardTransmission', models.CharField(blank=True, max_length=10)),
                ('Car_BodyType', models.CharField(blank=True, max_length=10)),
                ('Car_Drive', models.CharField(blank=True, max_length=10)),
                ('Car_Wheelbase', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_ID', models.CharField(blank=True, max_length=10)),
                ('Customer_Name', models.CharField(blank=True, max_length=10)),
                ('Customer_Phone', models.CharField(blank=True, max_length=10)),
                ('Customer_Addresss', models.CharField(blank=True, max_length=10)),
                ('Customer_Brithday', models.CharField(blank=True, max_length=10)),
                ('Customer_Occupation', models.CharField(blank=True, max_length=10)),
                ('Customer_Gender', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.CharField(blank=True, max_length=10)),
                ('Order_CreateDate', models.CharField(blank=True, max_length=10)),
                ('Order_PickupDate', models.CharField(blank=True, max_length=10)),
                ('Order_PickupStore', models.CharField(blank=True, max_length=10)),
                ('Order_Return_Store', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_Name', models.CharField(blank=True, max_length=10)),
                ('Store_Address', models.CharField(blank=True, max_length=10)),
                ('Store_Phone', models.CharField(blank=True, max_length=10)),
                ('Store_City', models.CharField(blank=True, max_length=10)),
                ('Store_State', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
