# Generated by Django 2.0.7 on 2018-07-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Car_EngineSize',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='Car_PriceNew',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='Car_SeriesYear',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='Car_TankCapacity',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
