# Generated by Django 2.0.7 on 2018-09-04 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crcapp', '0003_auto_20180904_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Order_Return_Store',
            new_name='Order_ReturnStore',
        ),
    ]
