# Generated by Django 2.0.7 on 2018-09-04 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crcapp', '0005_auto_20180904_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Order_PickupStore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crcapp.Store'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Order_ReturnStore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crcapp.Store'),
        ),
    ]
